language: ruby
bundler_args: --without development

rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.2
  - 2.4.0

env:
  matrix:
    - PATTERN=keen
    - PATTERN=synchrony

before_install:
  - gem update bundler
  - bundle --version
  - gem update --system
  - gem --version

script:
  - bundle exec rake pattern
